proxy:

  listen:
    address: "127.0.0.1"
    port: 8080
    
  services:
  
    - name: my-service
      domain: my-service.my-company.com
      hosts:
      - address: "10.0.0.1"
        port: 9090
      - address: "10.0.0.2"
        port: 9090
        
    - name: localtest
      domain: localhost
      hosts:
      - address: "127.0.0.1"
        port: 18171
      - address: 192.168.2.14
        port: 80      