{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "reverseproxy.serviceAccountName" . }}
  labels:
{{ include "reverseproxy.labels" . | nindent 4 }}
{{- end -}}
